data_values <- c(11, 13, 13, 15, 15, 16, 19, 20, 20, 20, 21, 21, 22, 23, 24, 
                 30, 40, 45, 45, 45, 71, 72, 73, 75)
bin_size <- 5  
bins <- split(data_values, ceiling(seq_along(data_values) / bin_size))
bin_mean <- lapply(bins, mean)  
smoothed_mean <- unlist(lapply(bins, function(bin) rep(mean(bin), length(bin))))
bin_median <- lapply(bins, median) 
smoothed_median <- unlist(lapply(bins, function(bin) rep(median(bin), length(bin))))
smoothed_boundaries <- unlist(lapply(bins, function(bin) {
  min_val <- min(bin)
  max_val <- max(bin)
  sapply(bin, function(x) ifelse(abs(x - min_val) < abs(x - max_val), min_val, max_val))
}))
print("Original Data:")
print(data_values)
print("Smoothed Data (Bin Mean):")
print(smoothed_mean)
print("Smoothed Data (Bin Median):")
print(smoothed_median)
print("Smoothed Data (Bin Boundaries):")
print(smoothed_boundaries)
